package com.dems.timeline.model;

public enum TimelineEventType {

    CASE_CREATED,
    CASE_STATUS_CHANGED,
    CASE_ASSIGNED,
    DOCUMENT_UPLOADED,
    DOCUMENT_VERSIONED,
    DOCUMENT_PROCESSED,
    EVIDENCE_REGISTERED,
    EVIDENCE_TRANSFERRED,
    USER_LOGIN,
    AUDIT_ALERT,
    COMMENT_ADDED,
    TASK_COMPLETED,
    REPORT_GENERATED,
    SHARE_CREATED,
    AI_PROCESSING_COMPLETED
}
