package com.dems.notification.model;

public enum NotificationType {

    CASE_ASSIGNED,
    DOCUMENT_SHARED,
    EVIDENCE_TRANSFERRED,
    EVIDENCE_CUSTODY_ALERT,
    AUDIT_ALERT,
    AI_PROCESSING_COMPLETE,
    AI_PROCESSING_FAILED,
    CASE_STATUS_CHANGED,
    SECURITY_ALERT,
    USER_MENTION,
    TASK_ASSIGNED,
    REPORT_GENERATED,
    SHARE_LINK_EXPIRING,
    UNAUTHORIZED_ACCESS_ATTEMPT
}
