/* eslint-disable @typescript-eslint/no-explicit-any */
declare module "lucide-react" {
  export const LayoutDashboard: any;
  export const FileText: any;
  export const FolderOpen: any;
  export const Shield: any;
  export const Users: any;
  export const ClipboardList: any;
  export const BarChart3: any;
  export const Settings: any;
  export const Search: any;
  export const Bell: any;
  export const Lock: any;
  export const Upload: any;
  export const Download: any;
  export const ChevronLeft: any;
  export const ChevronRight: any;
  export const X: any;
  export const Eye: any;
  export const EyeOff: any;
  export const Trash2: any;
  export const Plus: any;
  export const ArrowLeft: any;
  export const UserCheck: any;
  export const UserX: any;
  export const CheckCircle: any;
  export const XCircle: any;
  export const AlertTriangle: any;
  export const Clock: any;
  export const User: any;
  export const Link: any;
  export const Save: any;
  export const Database: any;
  export const TrendingUp: any;
  export const Calendar: any;
}
